### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "userName": "mateus1234",
  "email": "mateus1@gmail.com",
  "password": "12345"
}

###
GET http://localhost:8080/v1/users/39f58200-5943-45d8-8bcf-3c596fa866a1

###
GET http://localhost:8080/v1/users

###
DELETE http://localhost:8080/v1/users/d22d501a-f9c3-48a1-8b4c-cd4daaac6718

###
POST http://localhost:8080/v1/users/39f58200-5943-45d8-8bcf-3c596fa866a1/accounts
Content-Type: application/json

{
  "description": "conta de investimento",
  "street": "rua jose cobra",
  "number": 360
}

###
GET http://localhost:8080/v1/users/39f58200-5943-45d8-8bcf-3c596fa866a1/accounts

###

GET http://localhost:8080/v1/stocks

###

POST http://localhost:8080/v1/stocks
Content-Type: application/json

{
  "stockId": "PETR4",
  "description": "ação Petrobras"
}

###

POST http://localhost:8080/v1/accounts/96b4676d-91ff-4915-b8e2-b7646150c4b6/stocks
Content-Type: application/json

{
  "stockId": "MGLU4",
  "quantity": 100
}

###

GET http://localhost:8080/v1/accounts/96b4676d-91ff-4915-b8e2-b7646150c4b6/stocks

###
GET https://brapi.dev/api/quote/PETR4
Authorization: Bearer
